altar/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from altar.views import attendance, authentication, branch, category, coaches, equipment, games, landing, players, training

# Create Here
urlpatterns = [
    # Authentication URLs
    path('login/', authentication.LoginView.as_view(), name='login'),
    path('password-reset', authentication.ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password-reset-confirm.html'), name='password-reset-confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password-reset-complete.html'), name='password_reset_complete'),
    path('verification', authentication.VerificationEmail.as_view(), name='verification'),
    path('logout/', authentication.LogoutView.as_view(), name='logout'),

    # Index URLs
    path("", landing.IndexView.as_view(), name='index'),

    # Dashboard URLs
    path('dashboard/', landing.DashboardView.as_view(), name='dashboard'),

    # Categories URLs
    path('categories/', category.CategoriesView.as_view(), name='categories'),
    path('delete-category/<int:category_id>', category.DeleteCategory.as_view(), name='delete_category'),

    # Equipments URLs
    path('equipments/', equipment.EquipmentsView.as_view(), name='equipments'),
    path('delete_equipment/<int:equipment_id>', equipment.DeleteEquipment.as_view(), name='delete_equipment'),

    # Branches URLs
    path('branches/', branch.BranchesView.as_view(), name='branches'),
    path('delete_branch/<int:branch_id>', branch.DeleteBranch.as_view(), name='delete_branch'),

    # Player URLs
    path('add-player/', players.AddPlayer.as_view(), name='add_player'),
    path('players/', players.PlayersList.as_view(), name='players'),
    path('player-details/<int:player_id>/', players.PlayerDetails.as_view(), name='player_details'),
    path('edit-player/<int:player_id>/', players.EditPlayer.as_view(), name='edit_player'),
    path('delete-player/<int:player_id>/', players.DeletePlayer.as_view(), name='delete_player'),

    # Coach URLs
    path('coaches/', coaches.CoachesView.as_view(), name='coaches'),
    path('coach/deactivate/<int:coach_id>/', coaches.DeactivateCoach.as_view(), name='deactivate_coach'),
    path('coach/reactivate/<int:coach_id>/', coaches.ReactivateCoach.as_view(), name='reactivate_coach'),

    # Training URLs
    path('training-management/', training.TrainingManagement.as_view(), name='training_management'),
    path('training_details/<int:training_id>/', training.TrainingDetails.as_view(), name='training_details'),

    # Attendance URLs
    path('attendance-management/', attendance.AttendanceManagement.as_view(), name='attendance_management'),
    path('record_attendance/<int:session_id>/', attendance.RecordAttendance.as_view(), name='record_attendance'),

    # Game URLs
    path('game-schedule/', games.game_schedule, name='game_schedule'),
    path('game-details/<int:game_id>/', games.game_details, name='game_details'),
    path('match-results/', games.match_results, name='match_results'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include('altar.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

altar/models/equipment.py
from django.db import models

from altar.models.branch import Branches

# Create here
class Equipments(models.Model):
    equipment_name = models.CharField(max_length=100, null=True, blank=True)
    equipment_number = models.IntegerField(default=0)
    equipment_branch = models.ForeignKey(Branches, on_delete=models.CASCADE, blank=True, null=True, related_name="equipment_branch")
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.equipment_name)

altar/forms/branch.py
from django import forms

from altar.models.branch import Branches

# Create here
class BranchForm(forms.ModelForm):
    branch = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Enter a branch e.g. Fedha, Baraka', 'class':'form-control'}))

    class Meta:
        model = Branches
        fields = ['branch',]

altar/forms/category.py
from django import forms

from altar.models.category import Categories

# Create here
class CategoryForm(forms.ModelForm):
    category = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Enter a category e.g. Under 9s, Under 11s', 'class':'form-control'}))

    class Meta:
        model = Categories
        fields = ['category',]

altar/forms/equipment.py
from django import forms

from altar.models.equipment import Equipments
from altar.models.branch import Branches

# Create here
class EquipmentForm(forms.ModelForm):
    equipment_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Enter the equipment name', 'class':'form-control'}))
    equipment_number = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'placeholder': 'Enter the equipment number', 'class': 'form-control'}))
    equipment_branch = forms.ModelChoiceField(required=False, queryset=Branches.objects.all(), widget=forms.Select(attrs={'class':'my-select', 'placeholder':'Choose a branch...'}))

    class Meta:
        model = Equipments
        fields = ['equipment_name', 'equipment_number', 'equipment_branch']

altar/views/equipment.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from altar.forms.equipment import EquipmentForm
from altar.models.equipment import Equipments

# Create your views here.
class EquipmentsView(LoginRequiredMixin, View):
    template_name = 'app/equipments.html'

    def get(self, request):

        context = {
            'form': EquipmentForm(),
            'equipments': Equipments.objects.all()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = EquipmentForm(request.POST)
        if 'add_equipment' in request.POST: # Check if form is for adding an equipment
            form = EquipmentForm(request.POST)
            if form.is_valid():
                equipment = form.save(commit=False)
                equipment.save()
                messages.success(request, f"{equipment.equipment_name} added and saved successfully.")
                return redirect ('equipments')
            else:
                messages.error(request, f"Failed to add.")
                form = EquipmentForm()

        elif 'edit_equipment' in request.POST: # Check if the form is for editing an equipment
            equipment_id = request.POST.get('equipment_id')
            equipment = get_object_or_404(Equipments, pk=equipment_id)
            edit_form = EquipmentForm(request.POST, instance=equipment)
            if edit_form.is_valid():
                edit_form.save()
                messages.success(request, f"Equipment edited and saved successfully.")
                return redirect('equipments')
            else:
                messages.error(request, f"Failed to edit.")
                edit_form = EquipmentForm(instance=equipment)

        context = {
            'form': form,
        }
        return render(request, self.template_name, context)


class DeleteEquipment(LoginRequiredMixin, View):
    def post(self, request, equipment_id):
        equipment = get_object_or_404(Equipments, id=equipment_id)
        equipment.delete()
        messages.info(request, f"Equipment deleted successfully")
        return redirect('equipments')

templates/app/branches.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- START: Main Content-->
<main>
    <div class="container-fluid site-width">
        
        <!-- START: Card Data -->
        <div class="row">
            <div class="col-12" style="margin-top:50px;">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">                             
                        <h4 class="card-title" style="font-size:20px;"><i class="fas fa-code-branch mr-2"></i> <b>Branches</b></h4> 

                        {% if user.is_authenticated %}
                        <button data-toggle="modal" data-target="#cancel" class="btn btn-primary rounded-btn mb-2" style="float:right;"><i class="fas fa-plus-circle" style="margin-right:9px;"></i>Add Branch</button>
                        {% endif %}
                    </div>
                    <div class="card-body">                      
                        <div class="table-responsive">

                            {% if messages %}
                            <div class="messages">
                                {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            {% endif %}

                            <table id="example" class="display table dataTable table-striped table-bordered" >
                                <thead>
                                    <tr class="table-primary">
                                        <th scope="col">#</th>
                                        <th style="font-size: 15px;">Branch Name</th>
                                        <th style="font-size: 15px;">Number of Players</th>
                                        <th style="font-size: 15px;">Number of Coaches</th>
                                        <th style="font-size: 15px;">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for branch in branches %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{branch.branch}}</td>
                                        <td>{{branch.player_count}}</td>
                                        <td>{{branch.coach_count}}</td>
                                        <td>
                                            <a href="" data-toggle="modal" data-target="#edit{{ branch.id }}" class="btn btn-primary btn-sm mr-3" title="Edit"><i class="icon-pencil"></i></a>
                                            <a href="" data-toggle="modal" data-target="#delete{{ branch.id }}" class="btn btn-danger btn-sm mr-3" title="Delete"><i class="fas fa-trash-alt"></i></a>
                                        </td>
                                    </tr>

                                    <!-- Delete Branch Modal -->
                                    <div class="modal fade" id="delete{{ branch.id }}">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">
                                                        <i class="fas fa-trash mr-2"></i> Delete Branch
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="icon-close"></i>
                                                    </button>
                                                </div>
                                                <form class="add-note-form" action="{% url 'delete_branch' branch.id %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="branch_id" value="{{ branch.id }}">
                                                    <div class="modal-body">    
                                                        <p>Are you sure you want to delete: {{branch.branch}}?</p>                                           
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Edit Branch Modal -->
                                    <div class="modal fade" id="edit{{ branch.id }}">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">
                                                        <i class="fas fa-edit mr-2"></i> Edit Branch
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="icon-close"></i>
                                                    </button>
                                                </div>
                                                <form class="add-note-form" action="{% url 'branches' %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="edit_branch" value="true">
                                                    <input type="hidden" name="branch_id" value="{{ branch.id }}">
                                                    <div class="modal-body">                                               
                                                        <div class="form-group">
                                                            <label for="id_branch" class="col-form-label" style="font-size: medium;">Branch:</label>
                                                            <input type="text" name="branch" value="{{ branch.branch }}" class="form-control">
                                                        </div>                                        
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-success">Save Changes</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                            
                        </div>
                    </div>

                    <!-- Add Branch -->
                    <div class="modal fade" id="cancel">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">
                                        <i class="fas fa-plus-circle mr-2"></i> Add Branch
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <i class="icon-close"></i>
                                    </button>
                                </div>
                                <form class="add-note-form" action="{% url 'branches' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="add_branch" value="true">
                                    <div class="modal-body">                                               
                                        <div class="form-group">
                                            <label for="shift_name" class="col-form-label" style="font-size: medium;">Branch:</label>
                                            <p>{{form.branch}}</p>
                                        </div>                                        
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-success">Add Branch</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div> 

            </div>                  
        </div>
        <!-- END: Card DATA-->
    </div>

</main>
<!-- END: Content-->

<!-- SCRIPTS -->
<!-- START: Template JS-->
<script src="{% static '/vendors/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static '/vendors/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static '/vendors/moment/moment.js' %}"></script>
<script src="{% static '/vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>    
<script src="{% static '/vendors/slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- END: Template JS-->

<!-- START: APP JS-->
<script src="{% static '/js/app.js' %}"></script>
<!-- END: APP JS-->

<!-- START: Page Vendor JS-->
<script src="{% static '/vendors/datatable/js/jquery.dataTables.min.js' %}"></script> 
<script src="{% static '/vendors/datatable/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/vendors/datatable/jszip/jszip.min.js' %}"></script>
<script src="{% static '/vendors/datatable/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static '/vendors/datatable/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.print.min.js' %}"></script>
<!-- END: Page Vendor JS-->

<!-- START: Page Script JS-->        
<script src="{% static '/js/datatable.script.js' %}"></script>
<!-- END: Page Script JS-->


{% endblock %}

templates/app/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- START: Main Content-->
<main>
    <div class="container-fluid site-width">
        
        <!-- START: Card Data -->
        <div class="row">
            <div class="col-12" style="margin-top:50px;">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">                             
                        <h4 class="card-title" style="font-size:20px;"><i class="fas fa-list mr-2"></i> <b>Categories</b></h4> 

                        {% if user.is_authenticated %}
                        <button data-toggle="modal" data-target="#cancel" class="btn btn-primary rounded-btn mb-2" style="float:right;"><i class="fas fa-plus-circle" style="margin-right:9px;"></i>Add Category</button>
                        {% endif %}
                    </div>
                    <div class="card-body">                      
                        <div class="table-responsive">

                            {% if messages %}
                            <div class="messages">
                                {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                            {% endif %}

                            <table id="example" class="display table dataTable table-striped table-bordered" >
                                <thead>
                                    <tr class="table-primary">
                                        <th scope="col">#</th>
                                        <th style="font-size: 15px;">Category Name</th>
                                        <th style="font-size: 15px;">Number of Players</th>
                                        <th style="font-size: 15px;">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for category in categories %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{category.category}}</td>
                                        <td>{{category.player_count}}</td>
                                        <td>
                                            <a href="" data-toggle="modal" data-target="#edit{{ category.id }}" class="btn btn-primary btn-sm mr-3" title="Edit"><i class="icon-pencil"></i></a>
                                            <a href="" data-toggle="modal" data-target="#delete{{ category.id }}" class="btn btn-danger btn-sm mr-3" title="Delete"><i class="fas fa-trash-alt"></i></a>
                                        </td>
                                    </tr>

                                    <!-- Delete Category Modal -->
                                    <div class="modal fade" id="delete{{ category.id }}">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">
                                                        <i class="fas fa-trash mr-2"></i> Delete Category
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="icon-close"></i>
                                                    </button>
                                                </div>
                                                <form class="add-note-form" action="{% url 'delete_category' category.id %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="category_id" value="{{ category.id }}">
                                                    <div class="modal-body">    
                                                        <p>Are you sure you want to delete: {{category.category}}?</p>                                           
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Edit Category Modal -->
                                    <div class="modal fade" id="edit{{ category.id }}">
                                        <div class="modal-dialog modal-dialog-centered">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">
                                                        <i class="fas fa-edit mr-2"></i> Edit Category
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <i class="icon-close"></i>
                                                    </button>
                                                </div>
                                                <form class="add-note-form" action="{% url 'categories' %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="edit_category" value="true">
                                                    <input type="hidden" name="category_id" value="{{ category.id }}">
                                                    <div class="modal-body">                                               
                                                        <div class="form-group">
                                                            <label for="id_category" class="col-form-label" style="font-size: medium;">Category:</label>
                                                            <input type="text" name="category" value="{{ category.category }}" class="form-control">
                                                        </div>                                        
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-success">Save Changes</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                            
                        </div>
                    </div>

                    <!-- Add Category -->
                    <div class="modal fade" id="cancel">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">
                                        <i class="fas fa-plus-circle mr-2"></i> Add Category
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <i class="icon-close"></i>
                                    </button>
                                </div>
                                <form class="add-note-form" action="{% url 'categories' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="add_category" value="true">
                                    <div class="modal-body">                                               
                                        <div class="form-group">
                                            <label for="shift_name" class="col-form-label" style="font-size: medium;">Category:</label>
                                            <p>{{form.category}}</p>
                                        </div>                                        
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-success">Add Category</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    


                </div> 

            </div>                  
        </div>
        <!-- END: Card DATA-->
    </div>

</main>
<!-- END: Content-->

<!-- SCRIPTS -->
<!-- START: Template JS-->
<script src="{% static '/vendors/jquery/jquery-3.3.1.min.js' %}"></script>
<script src="{% static '/vendors/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static '/vendors/moment/moment.js' %}"></script>
<script src="{% static '/vendors/bootstrap/js/bootstrap.bundle.min.js' %}"></script>    
<script src="{% static '/vendors/slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- END: Template JS-->

<!-- START: APP JS-->
<script src="{% static '/js/app.js' %}"></script>
<!-- END: APP JS-->

<!-- START: Page Vendor JS-->
<script src="{% static '/vendors/datatable/js/jquery.dataTables.min.js' %}"></script> 
<script src="{% static '/vendors/datatable/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/vendors/datatable/jszip/jszip.min.js' %}"></script>
<script src="{% static '/vendors/datatable/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static '/vendors/datatable/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static '/vendors/datatable/buttons/js/buttons.print.min.js' %}"></script>
<!-- END: Page Vendor JS-->

<!-- START: Page Script JS-->        
<script src="{% static '/js/datatable.script.js' %}"></script>
<!-- END: Page Script JS-->



{% endblock %}